spring.datasource.url=${DB_URL:jdbc:mysql://mysql-167744fb-resq-project.i.aivencloud.com:23250/resq_db?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:avnadmin}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.application.name=resq-backend